[package]
name = "advent"
version = "0.1.0"
authors = ["Daniyar Mussakulov <dmussaku@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.18.2"
itertools = "0.11.0"